[phases.setup]
commands = ["pip install --upgrade pip"]

[phases.install]
commands = ["pip install setuptools", pip install -r requirements.txt"]

[phases.build]
commands = []

[phases.start]
commands = ["python main.py"]  # Ajusta esto según el archivo principal de tu aplicación
